### ISSUE TITLE
Reference of paper for detect-content

### ISSUE THREAD

**Issue by Wwwwei** [Breakthrough/PySceneDetect#94] opened 2019-02-28 13:03 UTC
Hello, thank you for this great work. PySceneDetect by detect-content has a good performance in my own application.  I really want to learn about how it works. Could you please provide the reference of paper about the detect-content algorithm?
Thank you.

**Comment by Breakthrough** [comment] 2019-03-17 18:52
Closing as duplicate of #62.

**Comment by Breakthrough** [comment] 2019-03-17 18:53
Hi @Wwwwei;

See issue #62 for some details about methods used in PySceneDetect.

Thanks!

**Closed by Breakthrough** 2019-03-17 18:52 UTC
Labels: status: duplicate
