### ISSUE TITLE
Support URL Streams via CLI/API

### ISSUE THREAD

**Issue by Fookiwara** [Breakthrough/PySceneDetect#188] opened 2020-10-08 19:22 UTC
Hello, its seems that cli cannot read video url:
"Path 'http://...' does not exist.
Any idea?
Regards

**Comment by adworacz** [comment] 2020-10-10 19:55
Likely because that's an HTTP URL. I'd doubt that the author wants to add HTTP retrieval to this library.

If you want to scan that video, I'd suggest downloading it locally first, then run the CLI on it.

**Comment by Breakthrough** [comment] 2020-10-26 15:19
It looks like OpenCV actually does support video stream URLs now, in addition to image sequences.  The following issues are all related to this issue:

 #152  #191

Once #152 is closed, it should allow you to use HTTP streams, however I can't give a definite timing for when this will work via the CLI.  In the meantime, from Python, you can use the `cv2.VideoCapture` class instead of a `scenedetect.VideoManager`.  Hope this helps, will keep this issue open until I figure out timing for the fix.

**Comment by Breakthrough** [comment] 2020-10-26 15:24
Marking this as a known issue for now as it relates to image sequences.  From the Python API, you can get around this by instantiating a `cv2.VideoCapture` object directly, as you would with an image sequence.  I was unaware that the OpenCV API works with HTTP streams, so this should be pretty easy to implement a workaround for.  It may be as simple as removing these two lines:

https://github.com/Breakthrough/PySceneDetect/blob/ccee5831e94d09fdbc9848ea40bb331d266450ef/scenedetect/video_manager.py#L231-L232

However I need to double check how the command line interface is implemented to make sure it won't cause any downstream effects.  Pinning this issue to raise awareness until a fix is available at least.  Thank you for the report!

**Comment by Breakthrough** [comment] 2021-01-10 04:58
This should be supported in the next release (v0.5.5).  You can test it now by checking out the v0.5.5 branch.

**Closed** 2021-01-10 05:05 UTC
Labels: improvement, known issue, status: completed

**Comment by Breakthrough** [comment] 2021-01-13 23:44
Technically this was a duplicate of #170, but marking it opposite because this is where most of the discussion went.

**Comment by jorie-peng** [comment] 2021-04-30 08:06
> It looks like OpenCV actually does support video stream URLs now, in addition to image sequences. The following issues are all related to this issue:
> 
> #152 #191
> 
> Once #152 is closed, it should allow you to use HTTP streams, however I can't give a definite timing for when this will work via the CLI. In the meantime, from Python, you can use the `cv2.VideoCapture` class instead of a `scenedetect.VideoManager`. Hope this helps, will keep this issue open until I figure out timing for the fix.

Hi, @Breakthrough I use python code as following, but it now work, do you know the error?
```
video_path = 'http://xxxx"
cap = cv2.VideoCapture(video_path)

video_manager = VideoManager([video_path])
stats_manager = StatsManager()
scene_manager = SceneManager(stats_manager)
```

and the error code is 
```
<ipython-input-49-2993cc392f39> in build_scenes(video_path)
     16 
---> 17     video_manager = VideoManager([video_path])
     18     stats_manager = StatsManager()
     19     scene_manager = SceneManager(stats_manager)

~/.conda/envs/torch/lib/python3.6/site-packages/scenedetect/video_manager.py in __init__(self, video_files, framerate, logger)
    362         # These VideoCaptures are only open in this process.
    363         self._cap_list, self._cap_framerate, self._cap_framesize = open_captures(
--> 364             video_files=video_files, framerate=framerate)
    365         self._end_of_video = False
    366         self._start_time = self.get_base_timecode()

~/.conda/envs/torch/lib/python3.6/site-packages/scenedetect/video_manager.py in open_captures(video_files, framerate, validate_parameters)
    243                        enumerate(cap_list) if not cap.isOpened()]
    244         if closed_caps:
--> 245             raise VideoOpenFailure(closed_caps)
    246 
    247         cap_framerates = [cap.get(cv2.CAP_PROP_FPS) for cap in cap_list]

VideoOpenFailure: OpenCV VideoCapture object failed to return True when calling isOpened().
```

Can I know the exact code about how to use scenedetect for url with python API

**Comment by Breakthrough** [comment] 2021-05-01 04:07
Hi @jorie-peng, what you wrote is correct.  Can you open the video using
OpenCV directly?  e.g. what happens if you do:

    import cv2
    cap = cv2.VideoCapture()
    cap.open('http://SOMEURL')

Thank you!

**Comment by jorie-peng** [comment] 2021-05-06 09:03
> Hi @jorie-peng, what you wrote is correct. Can you show the output of opening the video using OpenCV directly? e.g. what happens if you do: import cv2 cap = cv2.VideoCapture() cap.open('http://SOMEURL') print(cap.isOpened()) From the output you provided, the issue seems to be that the URL couldn't be opened by OpenCV. Thank you!

yes, it is the problem, Thanks!!
