### ISSUE TITLE
Flash detection

### ISSUE THREAD

**Issue by datbates** [Breakthrough/PySceneDetect#217] opened 2021-05-04 20:41 UTC
The best, easiest improvement I can see to make is to not detect flashes as scene changes.  Maybe an average of 4 frames would prevent false positives.  Thanks for this software.  Premiere Pro's detection was painful and yours is really helpful and slick.  I might put some effort in to helping solve this issue, but I'm in a hurry to convert my old videos so I can beat the Google Photos deadline ;-)

**Comment by Breakthrough** [comment] 2021-05-06 02:53
You might want to have a look through #35, @datbates, for some past discussion on the topic.  I actually did add this to the v0.6.x branch, but instead of averaging, it compares the last frame before the cut against the next N frames, ensuring that they *all* exceed threshold (`flicker_frames`).  This method specifically incurs no performance penalty except when a frame exceeds the threshold.

Truthfully, I haven't actually thought about averaging the video frames themselves, but that's an interesting idea.  My only concern is how to approach it in a performant manner, although I am sure that it can be done.

Closing as duplicate of #35 - feel free to continue the discussion there, or even test out v0.6.x to see if it works for your use case :)

**Closed by Breakthrough** 2021-05-06 02:53 UTC
