### ISSUE TITLE
Current implementation for seeking could be improved

### ISSUE THREAD

**Issue by obroomhall** [Breakthrough/PySceneDetect#162] opened 2020-05-10 14:50 UTC
**Description of Problem & Solution**
PySceneDetect seeking is slow because it grabs every frame up until the start_time of the desired frame, leading to unnecessarily long processing times for skipping in large files. Ideally this should be changed to use the proper method for skipping in OpenCV.

**Proposed Implementation:**
Should use the function `VideoCapture.set(cv2.CAP_PROP_POS_FRAMES, frame_to_jump_to-1)` rather than grab looping.

**Comment by obroomhall** [comment] 2020-05-10 14:56
Suggested implementation in https://github.com/Breakthrough/PySceneDetect/pull/163

**Comment by Breakthrough** [comment] 2020-05-27 00:00
Hi @obroomhall;

I haven't had a chance to look at this yet (will as soon as I can!), but some questions for you:
 - does this pass the PySceneDetect test cases?
 - have you validated that this works for a variety of different media formats?

I'm aware of the VideoCapture `set` method, but avoided it in the future due to inconsistent seeking (it was never frame perfect, thus unsuitable for the project).  Perhaps things have changed since I last validated it however, so I should come up with some more comprehensive test cases.

**Comment by obroomhall** [comment] 2020-05-27 21:53
Hi @Breakthrough,
Thanks for getting back to me!
1. Test cases are all passing, though we may need some more test cases here.
2. Validated for testvideo.mp4 from your resources branch, and also with an mkv file of my own. 

**Some notes:**
- Without this change, the library is an order of magnitude slower for my use case, skipping through large video files now happens in a matter of seconds versus previously a matter of minutes.
- It is probably also worth mentioning that because my mkv file was quite large (2.17GB, 25m 25s) it took 15 minutes to complete the test_many_videos_downscale_detect_scenes test as it detects scenes in the full video 3 times over. This is compared to running the full tests on testvideo.mp4 which only takes 18 seconds on my machine. It could be beneficial to cap the scene detection in this test to the first x seconds of the test file.

**Comment by Breakthrough** [comment] 2020-06-27 20:53
Closing as duplicate of #98.  Continue discussion there.

**Closed by Breakthrough** 2020-06-27 20:53 UTC
Labels: enhancement, status: accepted
