### ISSUE TITLE
--min-scene-len does not respect first scene

### ISSUE THREAD

**Issue by charlesvestal** [Breakthrough/PySceneDetect#105] opened 2019-06-11 13:36 UTC
**Bug/Issue Description:**
--min-scene-len returns scenes shorter than specified length at the beginning and end of a file

**Required Information:**
Provide the following information to assist with reporting the bug:
1. Provide a full copy of the command line options you are using, for example:

`scenedetect -i video.mp4 detect-threshold --min-scene-len 14000`

2. Add `-v debug -l BUG_REPORT.txt` to the beginning of the command, then re-run PySceneDetect and **attach the generated `BUG_REPORT.txt` file**.

[BUG_REPORT.txt](https://github.com/Breakthrough/PySceneDetect/files/3276702/BUG_REPORT.txt)

**Expected Behavior:**
A clear and concise description of what you *expected* to happen.

When specifying the `min-scene-len`, I would expect no scenes to be returned of below the length specified. It appears that _internal_ scenes are respected, but not the first or last segment.

For instance, if I have a 30m video with a fade to black at 1m, 15m and 29m. I would expect with a threshold of 300,000 (10 minutes), I would only have two 15m slices. Instead, I see the first fade detected, as well as the third, as the scenes in between are of sufficient length.  

Expected behavior would be that these are included as part of the adjacent scenes.

**Computing Environment:**
 - OS: osx
 - Python Version: 2.7
 - OpenCV Version: 4.1.0_2

**Comment by Breakthrough** [comment] 2019-06-11 21:54
Hi @charlesvestal;

Thanks for the submission, will definitely add this to the list of issues to address in the next version.

Much appreciated!

**Comment by Breakthrough** [comment] 2019-08-04 04:23
Hi @charlesvestal;

I think I have a fix for this issue I've committed to master just now.  Would you be willing to test the fix out to confirm that it has resolved your issue?

Thank you!

---------------------------

You can test the fix out by cloning the repo or [downloading it as an archive](https://github.com/Breakthrough/PySceneDetect/archive/master.zip), putting the video where you cloned/extracted the files, and run `scenedetect.py` directly inside of that folder, instead of using the `scenedetect` command).

**Comment by pgodwin** [comment] 2019-08-30 07:55
Having the same issue with detect-content as well.

**Comment by charlesvestal** [comment] 2019-08-30 10:59
> Having the same issue with detect-content as well.

Possibly related to the other issue, here? https://github.com/Breakthrough/PySceneDetect/issues/106

**Comment by Breakthrough** [comment] 2019-08-30 22:08
@pgodwin good catch, thank you.  Will work on that next.

@charlesvestal unfortunately they are not related in terms of the code changes which caused the bug, but that is one I still do have to get to for sure.

Thank you both!!

**Comment by Breakthrough** [comment] 2019-08-30 23:24
Alright, this should be fixed for the beginning of videos for both ThresholdDetector and ContentDetector in master as of 557bbc583cd729d703f72e4b0f42ceb62f07fe8f.

That being said, I'm not sure if it's worth it to apply the same logic to the end of the video - thoughts?  Is your expectation that even the last scene complies with the minimum scene length even in the event that can't be met (by merging it with a previous scene)?

If so I can consider adding a command line option for that as an enhancement, but would prefer it's tracked under a different issue if possible (just since this one has been root caused and a solution has been proposed).

**Comment by Breakthrough** [comment] 2019-08-31 01:40
Hey @charlesvestal;

The bugfix I applied is only for the first scene, since it's less correct to merge the last scene with it's predecessor simply because there weren't any frames left in the video.  I've updated the title of this issue to reflect that.

I personally don't feel that it's correct to apply this logic to the last scene, just because the last scene is generated out of the only remaining frames. If you (or anyone) happen to disagree with that logic, and feel like such an option *is* useful or adds value/utility to PySceneDetect, feel free to create a new feature/enhancement request.  If you can specify what you would call the command-line option to enable/disable the feature as well, that would be appreciated.

Thank you.

**Closed by Breakthrough** 2019-08-31 01:40 UTC
Labels: bug, status: in progress

**Comment by charlesvestal** [comment] 2019-08-31 06:03
Thanks! This appears to work as expected. And I think you're right in the sense of detecting scenes as this tool is intended to be used for. :) My use case was to split files containing multiple episodes of a show for instance, detecting black between episodes but ignoring other fades at the end of episodes. When used in conjunction with analyzed duration that should be a sufficient solve.

**Comment by Breakthrough** [comment] 2021-11-26 04:34
I should note that I've revisited this for v1.0 - several others have also felt this is inconsistent, so the default will be to always respect min_scene_len where possible by merging with the preceding scene, if any, otherwise the successor.   A new option will also allow you to adjust the distance which scenes can be to be considered for merging.

v1.0 should also provide many improvements and more knobs to turn when combining detector types as there will be proper support for discrete IN/OUT events instead of just CUT events (so, for example, now you can actually cut videos and leave out the times where there is no content).
