### ISSUE TITLE
Python output differs from CLI output!

### ISSUE THREAD

**Issue by arianaa30** [Breakthrough/PySceneDetect#108] opened 2019-07-11 18:54 UTC
I was using the scenedetect based on content using CLI and it was great. Then I tried the [exact python code](https://pyscenedetect.readthedocs.io/en/latest/examples/usage-python/) you provided on the homepage, but I see the output is different (python code prints an additional scene which never occurs). Is it a bug?

I'm using version 0.5.
```
from __future__ import print_function
import os

import scenedetect
from scenedetect.video_manager import VideoManager
from scenedetect.scene_manager import SceneManager
from scenedetect.frame_timecode import FrameTimecode
from scenedetect.stats_manager import StatsManager
from scenedetect.detectors import ContentDetector

STATS_FILE_PATH = 'testvideo.stats.csv'

def main():

    # Create a video_manager point to video file testvideo.mp4. Note that multiple
    # videos can be appended by simply specifying more file paths in the list
    # passed to the VideoManager constructor. Note that appending multiple videos
    # requires that they all have the same frame size, and optionally, framerate.
    video_manager = VideoManager(['test.mp4'])
    stats_manager = StatsManager()
    scene_manager = SceneManager(stats_manager)
    # Add ContentDetector algorithm (constructor takes detector options like threshold).
    scene_manager.add_detector(ContentDetector())
    base_timecode = video_manager.get_base_timecode()

    try:
        # If stats file exists, load it.
        if os.path.exists(STATS_FILE_PATH):
            # Read stats from CSV file opened in read mode:
            with open(STATS_FILE_PATH, 'r') as stats_file:
                stats_manager.load_from_csv(stats_file, base_timecode)

        start_time = base_timecode + 20     # frames: 00:00:00.667
        end_time = base_timecode + 40.0     # 00:00:20.000
        # Set video_manager duration to read frames from 00:00:00 to 00:00:20.
        video_manager.set_duration(start_time=start_time, end_time=end_time)

        # Set downscale factor to improve processing speed (no args means default).
        video_manager.set_downscale_factor()

        # Start video_manager.
        video_manager.start()

        # Perform scene detection on video_manager.
        scene_manager.detect_scenes(frame_source=video_manager)

        # Obtain list of detected scenes.
        scene_list = scene_manager.get_scene_list(base_timecode)
        # Like FrameTimecodes, each scene in the scene_list can be sorted if the
        # list of scenes becomes unsorted.

        print('List of scenes obtained:')
        for i, scene in enumerate(scene_list):
            print('    Scene %2d: Start %s / Frame %d, End %s / Frame %d' % (
                i+1, scene[0].get_timecode(), scene[0].get_frames(), scene[1].get_timecode(), scene[1].get_frames()))

        # We only write to the stats file if a save is required:
        if stats_manager.is_save_required():
            with open(STATS_FILE_PATH, 'w') as stats_file:
                stats_manager.save_to_csv(stats_file, base_timecode)

    finally:
        video_manager.release()

if __name__ == "__main__":
    main()
```

And the output is:

```
  0%|          | 0/1179 [00:00<?, ?frames/s]
 13%|#2        | 148/1179 [00:00<00:00, 1437.36frames/s]
 26%|##6       | 307/1179 [00:00<00:00, 1471.73frames/s]
 39%|###9      | 465/1179 [00:00<00:00, 1489.91frames/s]
 53%|#####3    | 625/1179 [00:00<00:00, 1512.68frames/s]
 65%|######5   | 767/1179 [00:00<00:00, 1479.00frames/s]
 78%|#######8  | 923/1179 [00:00<00:00, 1502.40frames/s]
 93%|#########3| 1101/1179 [00:00<00:00, 1559.55frames/s]
100%|##########| 1179/1179 [00:00<00:00, 1527.27frames/s]
List of scenes obtained:
    Scene  1: Start 00:00:00.667 / Frame 20, End 00:00:20.020 / Frame 600
    Scene  2: Start 00:00:20.020 / Frame 600, End 00:00:31.765 / Frame 952
    Scene  3: Start 00:00:31.765 / Frame 952, End 00:00:37.437 / Frame 1122
    Scene  4: Start 00:00:37.437 / Frame 1122, End 00:00:38.939 / Frame 1167
    Scene  5: Start 00:00:38.939 / Frame 1167, End 00:00:39.339 / Frame 1179
```

Whereas the CLI output (correct) is (`scenedetect --input test.mp4 -s file.csv time --start 0s --end 40s detect-content list-scenes`):

```
[PySceneDetect] Scene List:
-----------------------------------------------------------------------
 | Scene # | Start Frame |  Start Time  |  End Frame  |   End Time   |
-----------------------------------------------------------------------
 |      1  |           0 | 00:00:00.000 |         952 | 00:00:31.765 |
 |      2  |         952 | 00:00:31.765 |        1122 | 00:00:37.437 |
 |      3  |        1122 | 00:00:37.437 |        1167 | 00:00:38.939 |
 |      4  |        1167 | 00:00:38.939 |        1199 | 00:00:40.007 |
-----------------------------------------------------------------------
```
Attached is the test file.
[test.zip](https://github.com/Breakthrough/PySceneDetect/files/3383487/test.zip)

+ side question: how to get video duration? There is no `get_duration`!

**Comment by Breakthrough** [comment] 2019-07-11 21:29
Hi @arianaa30;

At first glance, this definitely appears to be a bug.  Thank you for providing the test file, that will be very useful when investigating the root cause.

As for your side question - very good point, I will consider adding a `get_duration` method to the VideoManager.  There is a [helper function called `get_num_frames(...)`](https://pyscenedetect-manual.readthedocs.io/en/latest/api/video_manager.html#scenedetect.video_manager.get_num_frames) which is used internally by the VideoManager to calculate the video length.  In the meantime, you may find that useful for your calculations.

Thank you for your submission & feedback!!

**Comment by arianaa30** [comment] 2019-07-11 21:41
Yeah that 20 frames didn't have any effects. I compiled from the latest github source code and then it worked!
Oh yeah duration is a must! Right. `get_num_frames(...) * FPS = duration`.

**Comment by arianaa30** [comment] 2019-07-11 21:44
One side question: How can I save a scene[i] as a file? In fact, say I need to save a video file with a length of `scene[i].start` to `scene[i].start + 10s`.

**Comment by Breakthrough** [comment] 2019-07-12 00:24
Hi @arianaa30;

Sorry, do you mean that with the latest source code from GitHub, you get the expected results now?

As for your side question, you can use [the video splitting functions](https://pyscenedetect-manual.readthedocs.io/en/latest/api/video_splitter.html), which requires you to pass in a scene list (which is a list of FrameTimecode pairs).  You can make a new scene list from the one returned by SceneManager to have the element you want, and modify the end timecode, then pass that to the video splitting function, e.g.

    output_scene_list = [ (scene_list[i][0], scene_list[i][0] + 10.0) ]

Thanks!

**Comment by arianaa30** [comment] 2019-07-12 08:03
Yes latest git code fixed it.

**Comment by Breakthrough** [comment] 2019-07-12 19:40
Closing issue due to being fixed in master; the fix will be included in the next release of PySceneDetect.

Opened new issue #109 to track requested API changes discussed above.

Thank you!

**Closed by Breakthrough** 2019-07-12 19:40 UTC
Labels: bug, status: accepted

**Comment by Breakthrough** [comment] 2019-07-21 18:39
Also @arianaa30, please note that currently, using [the get() method](https://pyscenedetect-manual.readthedocs.io/en/latest/api/video_manager.html#scenedetect.video_manager.VideoManager.get) will retrieve the total # of frames for all videos opened.  This may suit your needs in the meantime until #109 is closed.

**Comment by arianaa30** [comment] 2019-07-21 18:41
Ok thanks. Waiting for 109
