### ISSUE TITLE
Add parameter to specify the Scenes.csv file name resulted when using list-scenes

### ISSUE THREAD

**Issue by sgmihai** [Breakthrough/PySceneDetect#145] opened 2019-12-23 17:27 UTC
There is no way to specify the name of the .csv file where the scene list is saved (after reading the docs).
This is an important feature to have as rerunning with a different threshold parameter will result in the previous Filename+'-Stats.csv' file being overwritten (I think). Also it would be nice if the default behaviour would be to save it to something like Filename+Stats+Threshold.csv (movie.mkv-Stats-30.csv). Or even better, to include the minimum time length in its name too.

**Comment by wjs018** [comment] 2020-01-24 19:48
This is possible using the `-f` or `--filename` flag when running via the command line ([docs](https://pyscenedetect.readthedocs.io/en/latest/reference/command-line-params/#list-scenes-command)). For example, if you wanted to analyze a video with a threshold of 30 with the naming scheme you provided, the command would look like:

```bash
scenedetect -i movie.mkv detect-content -t 30 list-scenes -f $VIDEO_NAME-Stats-30.csv
```

**Comment by wjs018** [comment] 2020-01-28 05:32
I just got the chance to test this and using the `-f` flag for `list-scenes` does set the output filename for the `.csv` file as intended. However, the `$VIDEO_NAME` macro isn't working as intended. I will make a separate issue for this. In the meantime, you can manually set the output `.csv` filename using the `-f` flag.

**Comment by wjs018** [comment] 2020-01-28 15:04
See #149 for an example of how to do this properly using the `$VIDEO_NAME` macro. You need to enclose the filename parameter in single quotes so that bash doesn't read it in as a file.

**Comment by Breakthrough** [comment] 2020-07-29 18:01
Closing as invalid as both scene list and statsfile paths can be specified via the CLI.  As @wjs018 mentioned, the documentation can be improved in #149.

If this is incorrect, please feel free to re-open this issue or file a new one.  Thank you!

**Closed by Breakthrough** 2020-07-29 18:01 UTC
Labels: status: invalid
