### ISSUE TITLE
Read the video

### ISSUE THREAD

**Issue by li-an-sheng** [Breakthrough/PySceneDetect#191] opened 2020-10-26 03:53 UTC
- [ ] My video was transmitted via URL, but the error was reported in the line 'video_manager = VideoManager([video_path])'. After reading your comments, the file that can be opened with VideoCapture is shown, but it can be opened at 'Cap = cv2.videocapture (video_path)'
https://github.com/Breakthrough/PySceneDetect/issues/191#issue-729213948
I hope to get your help. Thank you

**Comment by Breakthrough** [comment] 2020-10-26 15:21
Hi @li-an-sheng;

This is correct, this seems to be related to #152.  There is a check in VideoManager that makes sure the path passed to the manager exists on disk, which is why image sequences or URLs don't work.  I did not know that OpenCV works now with HTTP streams, this is very useful information.

This seems to be a duplicate of #188, so I'll close this as a duplicate for now, but feel free to continue this discussion there.  Thanks for letting me know it works with `cv2.VideoCapture` as well, I'll indicate that in #188 so people know of the workaround until it is implemented.

Thank you for the report!!

**Closed by Breakthrough** 2020-10-26 15:21 UTC
