### ISSUE TITLE
Find 10 scenes while only generate 7 chips...

### ISSUE THREAD

**Issue by 2236262519** [Breakthrough/PySceneDetect#60] opened 2018-07-17 05:08 UTC
Hello!
This scenedetectpr works effeciently, but while I'm using it, I came across a problem.
The output tells me that 
Processing complete, found 10 scenes in video.
However ,the number of generated chips is only 7
Is there anything to do with the Muxing took 0 seconds?
Many thanks!

**Comment by Breakthrough** [comment] 2018-07-19 01:34
Just to confirm, do you mean PySceneDetect reports that it found 10 scenes, but only outputs 7 files?  Could you provide the output and full command you ran, as well as what scene numbers were output as videos?

Currently it uses mkvmerge to do video splitting, which doesn't work for every video.  PySceneDetect v0.5 (coming out soon) will have the option to use ffmpeg as well, which should solve this issue.

In the meantime, you can also generate the scene list as comma-separated values (CSV), and then copy-and-paste the timecodes into ffmpeg for creating start/end clips for each scene.

**Comment by Breakthrough** [comment] 2018-07-29 22:33
Closing as duplicate of #63 unless more information is provided to indicate that this issue is separate.

**Closed by Breakthrough** 2018-07-29 22:33 UTC
Labels: enhancement, status: more information required
