### ISSUE TITLE
Only for Webm format - starttime and endtime for the scenes are incorrect

### ISSUE THREAD

**Issue by ssharif-uvic** [Breakthrough/PySceneDetect#158] opened 2020-04-07 06:01 UTC
**Bug/Issue Description:**
The start time and endtime for webm video is incorrect.  It works for the same file when the file is converted to mp4.

**Required Information:**
Provide the following information to assist with reporting the bug:
1. Provide a full copy of the command line options you are using, for example:

`scenedetect --input 2020-01-13-160612.webm detect-content list-scenes save-images

Actual result,from the above command is:
-----------------------------------------------------------------------
 | Scene # | Start Frame |  Start Time  |  End Frame  |   End Time   |
-----------------------------------------------------------------------
 |      1  |           0 | 00:00:00.000 |      158839 | 01:28:14.633 |
 |      2  |      158839 | 01:28:14.633 |      159025 | 01:28:20.833 |
 |      3  |      159025 | 01:28:20.833 |      159051 | 01:28:21.700 |
 |      4  |      159051 | 01:28:21.700 |      159072 | 01:28:22.400 |
 |      5  |      159072 | 01:28:22.400 |      159095 | 01:28:23.167 |
 |      6  |      159095 | 01:28:23.167 |      159118 | 01:28:23.933 |
 |      7  |      159118 | 01:28:23.933 |      159139 | 01:28:24.633 |
 |      8  |      159139 | 01:28:24.633 |      159321 | 01:28:30.700 |
 |      9  |      159321 | 01:28:30.700 |      159344 | 01:28:31.467 |
 |     10  |      159344 | 01:28:31.467 |      159367 | 01:28:32.233 |
 |     11  |      159367 | 01:28:32.233 |      159385 | 01:28:32.833 |
 |     12  |      159385 | 01:28:32.833 |      159403 | 01:28:33.433 |
 |     13  |      159403 | 01:28:33.433 |      159423 | 01:28:34.100 |
 |     14  |      159423 | 01:28:34.100 |      159451 | 01:28:35.033 |
 |     15  |      159451 | 01:28:35.033 |      159472 | 01:28:35.733 |
 |     16  |      159472 | 01:28:35.733 |      159495 | 01:28:36.500 |
 |     17  |      159495 | 01:28:36.500 |      161281 | 01:29:36.033 |
 |     18  |      161281 | 01:29:36.033 |      161335 | 01:29:37.833 |
 |     19  |      161335 | 01:29:37.833 |      188952 | 01:44:58.400 |
 |     20  |      188952 | 01:44:58.400 |      188986 | 01:44:59.533 |
 |     21  |      188986 | 01:44:59.533 |      310728 | 02:52:37.600 |
 |     22  |      310728 | 02:52:37.600 |      311896 | 02:53:16.533 |
 |     23  |      311896 | 02:53:16.533 |      315332 | 02:55:11.067 |
 |     24  |      315332 | 02:55:11.067 |      315350 | 02:55:11.667 |
 |     25  |      315350 | 02:55:11.667 |      315372 | 02:55:12.400 |
 |     26  |      315372 | 02:55:12.400 |      315442 | 02:55:14.733 |
 |     27  |      315442 | 02:55:14.733 |      339696 | 03:08:43.200 |
 |     28  |      339696 | 03:08:43.200 |      339735 | 03:08:44.500 |
 |     29  |      339735 | 03:08:44.500 |      340162 | 03:08:58.733 |
-----------------------------------------------------------------------

2. Add `-v debug -l BUG_REPORT.txt` to the beginning of the command, then re-run PySceneDetect and **attach the generated `BUG_REPORT.txt` file**.

**Expected Behavior:**
This is what I expected which happened when I ran the same command with the mp4 version of the file:
-----------------------------------------------------------------------
 | Scene # | Start Frame |  Start Time  |  End Frame  |   End Time   |
-----------------------------------------------------------------------
 |      1  |           0 | 00:00:00.000 |      276305 | 02:33:30.167 |
 |      2  |      276305 | 02:33:30.167 |      276505 | 02:33:36.833 |
 |      3  |      276505 | 02:33:36.833 |      305761 | 02:49:52.033 |
 |      4  |      305761 | 02:49:52.033 |      305883 | 02:49:56.100 |
 |      5  |      305883 | 02:49:56.100 |      464125 | 04:17:50.833 |
 |      6  |      464125 | 04:17:50.833 |      464148 | 04:17:51.600 |
 |      7  |      464148 | 04:17:51.600 |      464182 | 04:17:52.733 |
 |      8  |      464182 | 04:17:52.733 |      464279 | 04:17:55.967 |
 |      9  |      464279 | 04:17:55.967 |      488556 | 04:31:25.200 |
 |     10  |      488556 | 04:31:25.200 |      488652 | 04:31:28.400 |
 |     11  |      488652 | 04:31:28.400 |      489303 | 04:31:50.100 |
-----------------------------------------------------------------------

**Computing Environment:**
 - OS: Ubuntu 18.04.4 LTS
 - Python Version: 3.6
 - OpenCV Version: 3.4.1

**Comment by Breakthrough** [comment] 2020-04-17 23:46
Hi @ssharif-uvic;

Can you provide the full debug log output to help with the analysis?

I'm fairly certain this is caused by the video having a variable frame rate.  Can you share some more details of how you converted the webm to mp4?  Can you share the effective framerate of both files, and if it's fixed or variable?

Thanks for the report.

**Comment by Breakthrough** [comment] 2020-07-29 18:25
Closing issue until further information can be provided for triaging.  Feel free to re-open or file a new issue at any time.  Thank you!

**Closed by Breakthrough** 2020-07-29 18:25 UTC
Labels: status: awaiting response
