### ISSUE TITLE
Progress regarding refactor

### ISSUE THREAD

**Issue by Hellowlol** [Breakthrough/PySceneDetect#57] opened 2018-06-29 01:20 UTC
I couldnt notice there was done anything refactoring lately, it that still underway? Or has it stopped? I have some ideas on how we can make this more modular. Atm it seems like the library is written to support the cli.

**Comment by Breakthrough** [comment] 2018-06-29 16:42
Hi @Hellowlol;

Thanks for the comment.  Indeed I realized the direction I was taking the project in v0.4 was primarily focused on the CLI as I was working on more high-level features at the time.  Indeed I am planning on reworking the structure of the entire project to make it more appropriate for extension.

My plan is to release v0.5 with an updated Python API by the end of July (I have not had time to work on the project all year until this week, coincidentally).  That being said, I am most open to any ideas or suggestions you might have that would improve the modularity of the project.

Thank you.

**Comment by Hellowlol** [comment] 2018-06-29 19:45
Im on holly day without a computer so this might be a bit brife, I’ll fix up it later.

For the cli I would add subcommands with options 

Fx: scenedetect -d (the rest of manager params and output options) detector1 -t 10 (rest of params for that detector) detector2 -options

Most should be moved inside manager. Cap should be a me so kw can use our own (reimplemented using threads) or just default to cap. 

Add a method that adds a a detector to the detector list

Move all args parsing outside the classes. This should be converted to keyword arguments 

I’ll add some code examples when I get home

**Comment by Breakthrough** [comment] 2018-07-02 23:13
Made some major progress to implementing a multiprocessing-based video decoder.  One thing I'm having trouble with here is using the multiprocessing module to pass images via a queue to the main process.   I have successfully put several images into the queue, but on the decoding process side, it raises a queue.Empty error infrequently, even if there are other objects in the queue.  Other times, it blocks indefinitely, not sure why this occuring.  Any thoughts?

It seems that the frames get put into the queue properly, just the main process can't seem to get them out of the queue...

**Comment by Breakthrough** [comment] 2018-07-03 01:38
One other strange issue is with process termination.  Everything works fine if I terminate the main loop while it's working, but if I put in a short sleep statement, then the join() method never works (even if I verify that the return statement is executed with a print statement).  Will try to upload it later, there's a test case that demonstrates the issue.

**Comment by Hellowlol** [comment] 2018-07-03 07:07
There was some comments on the blog about py3 being slow and the need for a lock. Have you posted your code anywhere?

**Comment by Breakthrough** [comment] 2018-07-03 18:19
Hey @Hellowlol;

I've attached to this comment a copy of the development version I'm working on (sorry I still need to push it to Git in a separate branch, as it breaks everything).  Started from scratch on a lot of stuff.

There's only unit tests, run with `python -m unittest discover -v`.  Specifically, check out the `test_content_detect_asynchronous` test case in test_scene_manager.py.  For some reason, whenever I add a delay long enough for the video manager process to queue all frames in the video (2 seconds is usually long enough for a few seconds of the test video), the video manager process becomes unjoinable from the main process, and I'm unable to obtain the return code (even though I know the process thread_func has returned a value).

Interestingly enough, without the delay, this issue doesn't occur, and the process is joinable, and I see the return code in the main process.

Didn't know about the py3 thing being slow, maybe I should test this on Python 2, but not sure if it's worth supporting v2.x moving forwards (the v0.5-rewrite attached to this post has no real provisions for Python 2 yet outside of the print statement, need to add something for handling the Queue->queue rename at runtime in the scenedetect.platform module).
[PySceneDetect-v0.5-dev.zip](https://github.com/Breakthrough/PySceneDetect/files/2160580/PySceneDetect-v0.5-dev.zip)

**Comment by Hellowlol** [comment] 2018-07-03 19:19
I added a lock and test_content_detect_asynchronous  worked. But the memory usage was 15 times higher. I didnt notice any speed increase but the laptop im using now so dog slow so i didnt except anything to be faster.

**Comment by Breakthrough** [comment] 2018-07-03 19:35
Wow that is a significant increase indeed.  Where did you add the lock, and around what object, the queue?  If you have a link to the comments you mentioned before, wouldn't mind having a look (or feel free to upload the modified code).

I'm starting to wonder if there's a logic error with the way I'm handling this, since this should theoretically be faster using multiprocessing, although perhaps the overhead of doing I/O in a separate process outweighs the performance gains?

Regardless, I'm going to just go forwards in the meantime with cleaning up the VideoManager class, maybe moving the Async version into a separate module, and continue going forwards with reworking the SceneManager (taking into account the changes you mentioned), the SceneDetectors, and add a StatsticsManager key/value store for frame metrics rather than relying on a passed frame_metrics dict.

Other than that, any comments in regards to how the v0.5 API is shaping up?  I'm hoping focusing on test-driven development for this release will help create an environment where the API is much more stable and focused on Python-first rather than CLI-first.

**Comment by Hellowlol** [comment] 2018-07-03 19:47
I created a new file called lock.py with a single variable called LOCK = RLock()

i imported that in video_manager and added that to line 523
and added the lock to scene_manager to line 92.

Ill do some more testing later. The comments are in the blog post i linked to you. Just scoll down ;)

**Comment by Hellowlol** [comment] 2018-07-03 20:03
Also the results from the scene_manager should be a class or a duct so it’s possible to know what detector found what

**Comment by Breakthrough** [comment] 2018-07-03 20:35
@Hellowlol After calling detect_scenes(...) my plan was for it to return the # of scenes detected, and, have you obtain the results by calling get_scene_list() - are you thinking that the actual detect_scenes(...) function should just return the scene list instead?

Since the scene numbers will always be contiguous, was thinking it should just return a list of either FrameTimecodes of the scene start frames, or tuples of (start_frame, end_frame).  Can have it return a dict as well though, where the keys are the integer scene numbers (might work better since then can call the first scene Scene 1?).

I'll also look into the idea of returning a dict of `SceneResult` objects as you suggested, which the more I think about it, the more it makes sense, since then the SceneResult object can contain the scene's start timecode, end timecode, duration, and optionally, the actual first/last frames of the scene for thumbnail generation purposes.

**Comment by Breakthrough** [comment] 2018-07-03 21:46
Also, what is your opinion on supporting Python 2 versus 3?  What do you use, and what do you think the project should support officially?

One thing I'd like to use is type hints, but that's thrown a wrench into my testing of the code using Py2.7 (was going to see if it helped the performance).  One way around it is to use [comment-like type hints](https://mypy.readthedocs.io/en/latest/python2.html#type-checking-python-2-code), but was wondering if you had dealt with this issue before.

It's basically between just using commented type hints, which is extra maintenance cost IMHO, versus official PEP 484 type hints, and losing compatibility with Python 2.x...

**Comment by Hellowlol** [comment] 2018-07-03 23:06
I don’t think the type hits make the code more readable so I don’t use it. I support py2 and py3 for all my project but I gonna rip it out when eol for py 2 is reached. So that’s up to you.

I think it should return the class and use get_scene_list() but return  dict or a scene result or some kind. The user or the cli tool can concat all the scenes.

**Comment by Breakthrough** [comment] 2018-07-04 00:18
Gotcha, thanks for your input.  Decided to go with just using comments for type hints to get it working with Python 2.

Got it up and running again on Py2.7, but no change in runtime behaviour... Synchronous version still seems to be faster on both Py2 and 3.

Results for 20 second run of 720p video using `multiprocessing`:
 - Python 2:  Synchronous = 17.4 sec, Asynchronous = 18.1 sec
 - Python 3:  Synchronous = 14.6 sec, Asynchronous = 15.5 sec

And using `threading` and `Thread` instead of `multiprocessing` and `Process`:
 - Python 2:  **Synchronous = 17.4 sec, Asynchronous = 16.5 sec**
 - Python 3:  Synchronous = 14.6 sec, Asynchronous = 17.2 sec

Very interesting that only using `threading` and Python 2 is the threaded version faster, and not by very much either... Guess I'll stick to multiprocessing, interesting how much faster Python 3 runs than Python 2 for a lot of stuff though.

**Comment by Breakthrough** [comment] 2018-07-05 02:02
Also, preview of the direction I'm going with the new sub-commands:

    scenedetect input -i video.mp4 -s video.stats.csv time --duration 10s detect-content -t 32 detect-threshold -t 20 split --precise output --directory output_dir/

**Comment by Breakthrough** [comment] 2018-07-07 00:04
Progress on the v0.5 release can be tracked in a separate branch now, v0.5-dev ( https://github.com/Breakthrough/PySceneDetect/tree/v0.5-dev ).  I will keep this issue open until v0.5 is complete, at which time it will be closed to signal the release.

**Comment by Breakthrough** [comment] 2018-07-07 23:03
Closing issue as duplicate of #27 

Discussion may be continued there.

**Comment by Breakthrough** [comment] 2018-07-22 23:30
Hey @Hellowlol;

Just an update for you, the v0.5 branch should now be stable enough for people to start testing with.  The only features remaining to be implemented is the re-addition of video splitting support, and generation of start/end frame images for each detected scene.  Also added a progress bar if you have the `tqdm` library installed.

Other than that, all other features (stats file, scene list, content/threshold algos) are all up and running with the newer and much cleaner CLI interface and, finally, a proper and much-improved API.  Run `scenedetect.py help` to get a sample of how the new CLI functions, and check out `api_test.py`  for a sample of the new Python API.

Thanks again for your feedback and input, am looking forwards to any other comments you might have before preparing the v0.5 release.

**Comment by Hellowlol** [comment] 2018-07-24 10:42
I havnt had time to play with it, but i think it would be nice to have some examples on how to use the api on the readme. Currently any users would need to check the source code to figure out how to use it.

Ill do some testing and see if can see any other thing.

**Closed** 2018-08-01 16:55 UTC
Labels: status: duplicate
