### ISSUE TITLE
Error: Invalid end time for '--split' in '--split parts

### ISSUE THREAD

**Issue by raj6996** [Breakthrough/PySceneDetect#81] opened 2018-09-27 07:14 UTC
[SD.Issue#81.txt](https://github.com/Breakthrough/PySceneDetect/files/2422873/SD.Issue.81.txt)
**Computing Environment:**
 - OS: [e.g. Windows 10, 64bit
 - Python Version: 64bit 3.7
 - OpenCV Version: latest

**Comment by Breakthrough** [comment] 2019-04-05 18:54
Hi @raj6996;

This is interesting, it seems like the video you gave somehow detected a scene at frame 0?  I'll have to add a check to PySceneDetect to handle this case specifically.

Would you be able to share the source video you used for this?  (Just the first few seconds is sufficient - if you can't share the video though, no worries.)

Thanks for your report!

**Comment by Breakthrough** [comment] 2019-08-31 02:02
Hey @raj6996;

What version of PySceneDetect were you using here?  Do you still get the same issue on v0.5.1/v0.5.1.1?  Could you provide me a sample file that triggers the bug, if so?

I think this might be caused by a video where the first frame already exceeds the threshold, but just want to make sure this is the correct root cause and I'm diagnosing/working on the same issue that you are describing.

Thank you!

**Comment by Breakthrough** [comment] 2020-07-29 18:16
Closing issue until further information can be provided.  Thank you!

**Closed by Breakthrough** 2020-07-29 18:16 UTC
Labels: bug, status: awaiting response
