### ISSUE TITLE
Return SyntaxWarning errors

### ISSUE THREAD

**Issue by marillat** [Breakthrough/PySceneDetect#400] opened 2024-06-11 05:42 UTC
With PySceneDetect 0.6.4 debian unstable amd64 python 3.11.9
I see the warnings

```
/usr/lib/python3/dist-packages/scenedetect/_cli/__init__.py:927: SyntaxWarning: invalid escape sequence '\$'
  help='Filename format to use for the scene list CSV file. You can use the $VIDEO_NAME macro in the file name. Note that you may have to wrap the name using single quotes or use escape characters (e.g. -f=\$VIDEO_NAME-Scenes.csv).%s'
/usr/lib/python3/dist-packages/scenedetect/_cli/__init__.py:1065: SyntaxWarning: invalid escape sequence '\$'
  """Split input video using ffmpeg or mkvmerge.
/usr/lib/python3/dist-packages/scenedetect/_cli/__init__.py:1208: SyntaxWarning: invalid escape sequence '\$'
  """Create images for each detected scene.
```

**Comment by Breakthrough** [comment] 2024-06-11 14:11
Thanks for letting me know, I should have a fix for this within a day or two.

Could you share the output of running the `scenedetect version` command?  I'm having trouble reproducing this locally, and don't see the warnings in any of the Python 3.12 builds ([example](https://github.com/Breakthrough/PySceneDetect/actions/runs/9459164563/job/26055805081)).

This is definitely an issue, and looks like this was [upgraded from DeprecationWarning to SyntaxWarning in Python 3.12](https://docs.python.org/3/whatsnew/3.12.html#other-language-changes).  I want to make sure these errors show up in builds here on Github so we can make sure it does not reoccur in the future, so I wonder if perhaps one of the third-party libraries being used is changing the default warning filter.

**Comment by marillat** [comment] 2024-06-11 15:08
I see these warnings when the source is byte compiled
byte compilation is done when the package is installed.
Debian package from https://www.deb-multimedia.org/
```
$ sudo  py3compile -f -p python3-scenedetect 
/usr/lib/python3/dist-packages/scenedetect/_cli/__init__.py:927: SyntaxWarning: invalid escape sequence '\$'
  help='Filename format to use for the scene list CSV file. You can use the $VIDEO_NAME macro in the file name. Note that you may have to wrap the name using single quotes or use escape characters (e.g. -f=\$VIDEO_NAME-Scenes.csv).%s'
...
```

**Closed** 2024-11-10 02:00 UTC
Labels: bug
