### ISSUE TITLE
Scene Detect using a specific part

### ISSUE THREAD

**Issue by kimlia545** [Breakthrough/PySceneDetect#238] opened 2021-09-03 08:18 UTC
Hi, thank you for your work.
Is it possible to detect frames based on the change of a specific part rather than the whole frame?
For example, if the number at the top of the frame changes, it is recognized that the frame has changed.
Looking forward for your answer.

**Comment by Breakthrough** [comment] 2021-09-04 14:36
This was just asked in #234 actually - closing as duplicate of #234, feel free to continue the discussion there.

**Closed by Breakthrough** 2021-09-04 14:36 UTC

**Comment by Breakthrough** [comment] 2021-09-04 14:44
Also if you have any samples you can provide, if you can add them to #234, that would be helpful.  Thank you!

**Comment by Breakthrough** [comment] 2021-09-29 00:33
Sorry I linked you to the wrong issue - this is a duplicate of #147.
