### ISSUE TITLE
unstable results

### ISSUE THREAD

**Issue by peratchi** [Breakthrough/PySceneDetect#135] opened 2019-11-21 03:48 UTC
Hi,

I am getting different scene results in different machines. even though I have installed the same version of packages(including all dependencies) in both machines 

Version of packages installed in both machines:

scenedetect | 0.5.1.1 | 0.5.1.1
ffmpeg-python | 0.2.0 | 0.2.0
imageio | 2.5.0 | 2.6.1
imageio-ffmpeg | 0.3.0 | 0.3.0
opencv-python | 4.1.1.26 | 4.1.1.26

**result i got in machine 1:**

\| Scene # \| Start Frame \|  Start Time    \|  End Frame  \|     End Time   \|
--
-----------------------------------------------------------------------
\|        1  \|           0 \| 00:00:00.000 \|           4 \| 00:00:00.133 \|
\|        2  \|           4 \| 00:00:00.133 \|          19 \| 00:00:00.634 \|
\|        3  \|          19 \| 00:00:00.634 \|          34 \| 00:00:01.134 \|
\|        4  \|          34 \| 00:00:01.134 \|          49 \| 00:00:01.635 \|
\|        5  \|          49 \| 00:00:01.635 \|          64 \| 00:00:02.135 \|
\|        6  \|          64 \| 00:00:02.135 \|          79 \| 00:00:02.636 \|
\|        7  \|          79 \| 00:00:02.636 \|          94 \| 00:00:03.136 \|
\|        8  \|          94 \| 00:00:03.136 \|         109 \| 00:00:03.637 \|
\|        9  \|         109 \| 00:00:03.637 \|         125 \| 00:00:04.171 \|
\|       10  \|         125 \| 00:00:04.171 \|         140 \| 00:00:04.671 \|
\|       11  \|         140 \| 00:00:04.671 \|         155 \| 00:00:05.172 \|
\|       12  \|         155 \| 00:00:05.172 \|         180 \| 00:00:06.006 \|
\|       13  \|         180 \| 00:00:06.006 \|         184 \| 00:00:06.139 \|

**in machine 2:**

\| Scene # \| Start Frame \|  Start Time    \|  End Frame  \|     End Time   \|
--
-----------------------------------------------------------------------
\|        1  \|           0 \| 00:00:00.000 \|           4 \| 00:00:00.133 \|
\|        2  \|           4 \| 00:00:00.133 \|          19 \| 00:00:00.634 \|
\|        3  \|          19 \| 00:00:00.634 \|          34 \| 00:00:01.134 \|
\|        4  \|          34 \| 00:00:01.134 \|          49 \| 00:00:01.635 \|
\|        5  \|          49 \| 00:00:01.635 \|          64 \| 00:00:02.135 \|
\|        6  \|          64 \| 00:00:02.135 \|          79 \| 00:00:02.636 \|
\|        7  \|          79 \| 00:00:02.636 \|          94 \| 00:00:03.136 \|
\|        8  \|          94 \| 00:00:03.136 \|         109 \| 00:00:03.637 \|
\|        9  \|         109 \| 00:00:03.637 \|         125 \| 00:00:04.171 \|
\|       10  \|         125 \| 00:00:04.171 \|         140 \| 00:00:04.671 \|
\|       11  \|         140 \| 00:00:04.671 \|         155 \| 00:00:05.172 \|
\|       12  \|         155 \| 00:00:05.172 \|         180 \| 00:00:06.006 \|

can anyone please help me

**Comment by Breakthrough** [comment] 2019-11-24 22:04
Hi @peratchi;

Indeed this is a very interesting result.  Have you confirmed that you are using a bit-for-bit identical copy of the same video on both machines?  Can you share more information about the two machines?  Do they have the same hardware/operating system, or is it different?  Can you replicate this behaviour in a virtual machine?  What version of Python are you using?

Lastly, how are you running and comparing the output?  It seems like on machine #2 it detected the same scenes except for the last one.  This indicates that the detection matched on both machines until that point, at which one process appears to have prematurely terminated.

Can you provide an output debug log as well?  Add `-v debug -l BUG_REPORT.txt` to the beginning of the command, then re-run PySceneDetect and attach the generated BUG_REPORT.txt` file for both machines.

Thank you for your report.

**Comment by peratchi** [comment] 2020-03-17 06:23
Hi @Breakthrough ,

PFB content of BUG_REPORT.txt which i got on both machines.

Machine 1: (OpenCV = 4.1.1.26, OS = Ubuntu 18.04.3 LTS, 8 Core /16GB RAM)
INFO: __init__.scenedetect_cli(): Version: v0.5.1
INFO: __init__.scenedetect_cli(): Info Level: debug
DEBUG: context.parse_options(): Parsing program options.
DEBUG: context._init_video_manager(): Initializing VideoManager.
INFO: video_manager.__init__(): Loaded 1 video, framerate: 24.00 FPS, resolution: 1280 x 720
INFO: video_manager.set_downscale_factor(): Downscale factor set to 5, effective resolution: 256 x 144
DEBUG: context.parse_options(): VideoManager initialized.
DEBUG: __init__.detect_content_command(): Detecting content, parameters:
  threshold: 30, min-scene-len: 15
INFO: context.list_scenes_command(): Scene list CSV file name format:
  $VIDEO_NAME-Scenes.csv
DEBUG: context.process_input(): Processing input...
INFO: context.process_input(): Detecting scenes...
INFO: context.process_input(): Processed 14308 frames in 48.6 seconds (average 294.45 FPS).
INFO: context.process_input(): Detected 130 scenes, average shot length 4.6 seconds.
INFO: context.process_input(): Writing scene list to CSV file:
  BigBuckBunny-Scenes.csv
INFO: context.process_input(): Scene List:

Machine 1: (OpenCV = 4.1.1.26, OS = Ubuntu 18.04.4 LTS, 16 Core /32GB RAM)
INFO: __init__.scenedetect_cli(): Version: v0.5.1
INFO: __init__.scenedetect_cli(): Info Level: debug
DEBUG: context.parse_options(): Parsing program options.
DEBUG: context._init_video_manager(): Initializing VideoManager.
INFO: video_manager.__init__(): Loaded 1 video, framerate: 24.00 FPS, resolution: 1280 x 720
INFO: video_manager.set_downscale_factor(): Downscale factor set to 5, effective resolution: 256 x 144
DEBUG: context.parse_options(): VideoManager initialized.
DEBUG: __init__.detect_content_command(): Detecting content, parameters:
  threshold: 30, min-scene-len: 15
INFO: context.list_scenes_command(): Scene list CSV file name format:
  $VIDEO_NAME-Scenes.csv
DEBUG: context.process_input(): Processing input...
INFO: context.process_input(): Detecting scenes...
INFO: context.process_input(): Processed 14300 frames in 37.3 seconds (average 382.95 FPS).
INFO: context.process_input(): Detected 131 scenes, average shot length 4.6 seconds.
INFO: context.process_input(): Writing scene list to CSV file:
  BigBuckBunny-Scenes.csv

**Comment by Breakthrough** [comment] 2020-03-30 01:15
Can you verify that the file size (and hash) is the *exact* same on both machines?  Is the behaviour repeatable?  If you run this on a third machine, which does it agree with (or can you share the video)?  The fact that just the number of frames it was able to decode makes me think it's either due to a corrupted or nonstandard video stream, or the actual version of ffmpeg that's installed on the systems differ (*not* the package for Python but the system libraries that OpenCV uses).

Are both systems the same machine architecture (32 vs 64 bit OS)?

**Comment by Breakthrough** [comment] 2020-07-29 18:05
Hi @peratchi;

Are you still experiencing this issue?  I would like to close it if not - could you perhaps try on a new version of PySceneDetect?

Thanks!

**Closed** 2020-08-08 18:08 UTC
Labels: status: awaiting response
