### ISSUE TITLE
Errors while running the file

### ISSUE THREAD

**Issue by rijutawankar** [Breakthrough/PySceneDetect#55] opened 2018-06-16 05:34 UTC
I took the example from python interface with pyscendetect which was given in the official website of pyscenedetect. I am trying to detect the changed scenes in the video to implement it for video forgery project. The example is giving me this error. I have installed the pyscenedetect package still it is showing some files are not imported. What do you think is going wrong and do you think pyscenedetect will be good module for making video forgery detection in realtime. Please help....

(rijuta) rijuta@rijuta-HP-Notebook:~/Video_analytics/PySceneDetect-0.4/python-scene-detection-tutorial-master/examples$ python scenedetect_example.py testvideo.mp4
Parsing video testvideo.mp4...
Video Resolution: 1280 x 720
Traceback (most recent call last):
  File "scenedetect_example.py", line 58, in <module>
    main()
  File "scenedetect_example.py", line 37, in main
    path, scene_list)
  File "build/bdist.linux-x86_64/egg/scenedetect/__init__.py", line 96, in detect_scenes_file
AttributeError: 'list' object has no attribute 'timecode_list'

**Comment by Breakthrough** [comment] 2018-06-19 01:02
Hi @rijutawankar;

My apologies, I have not had a chance yet to update the website documentation with the recent API changes in v0.4.  There are some outstanding problems with the direction I was going in as per some feedback here on Github, and I have not had a chance to update it.  The website documentation is for v0.3.2 and prior.

In the meantime, you might want to take a look at [the main() function in __init__.py](https://github.com/Breakthrough/PySceneDetect/blob/08931ca1525c247848a12bb60312f38e847171b6/scenedetect/__init__.py#L281) as a guide on how to detect scenes with the new API, but I don't know how useful this will be as it will change in the future.  As you can see, one of the issues is the heavy reliance on the args variable, which will be fixed to stabilize the API in the following release.

Sorry about that.

**Comment by Breakthrough** [comment] 2018-06-19 01:02
Duplicate of #27

**Closed by Breakthrough** 2018-06-19 01:02 UTC
Labels: status: duplicate

**Comment by adityap31** [comment] 2019-03-20 09:33
> Duplicate of #27

Hello Breakthrough,
I am still facing this issues. Can you help.
AttributeError: module 'scenedetect' has no attribute 'detect_scenes_file

**Comment by adityap31** [comment] 2019-03-20 09:33
Hello Breakthrough,
I am still facing this issues. Can you help.

`AttributeError: module 'scenedetect' has no attribute 'detect_scenes_file`

**Comment by Breakthrough** [comment] 2019-03-21 01:57
Hi @adityap31;

There is no detect_scenes_file method.  See the following 2 pages for some examples of the API.

https://pyscenedetect.readthedocs.io/en/latest/examples/usage-python/

https://pyscenedetect-manual.readthedocs.io/en/latest/api/scene_manager.html#usage-example


Thanks.

**Comment by adityap31** [comment] 2019-03-21 19:50
Hi Breakthrough,
The method is present. Check below link. Please correct me if I am wrong.

https://github.com/Breakthrough/PySceneDetect/issues/32

**Comment by Breakthrough** [comment] 2019-03-22 01:10
@adityap31 that was referring to the old version, v0.4.  That method is no longer present in v0.5.

**Comment by adityap31** [comment] 2019-03-22 04:35
Okay. And the usage example link you have already shared, right ?

**Comment by Breakthrough** [comment] 2019-05-19 22:24
Hi @adityap31;  Yes, there are two different examples at the links above.
