### ISSUE TITLE
Need to save Images to desired folder or disable

### ISSUE THREAD

**Issue by raj6996** [Breakthrough/PySceneDetect#58] opened 2018-07-14 07:15 UTC
scenedetect -i "O:\B.mkv" -d content -si -df 4 -o O:\ffmpeg\bin\O\3.mkv
I need two option
1. Save all extracted images to desired folder rather than spread out PySceneDetect-0.4-win64-portable folder, it will be cozy to manage!
Or
2. Disable all image when I choose only video files.

**Comment by Breakthrough** [comment] 2018-07-14 15:55
Hi @raj6996;

The next version of PySceneDetect (v0.5) will allow you to specify the output directory all files PySceneDetect outputs, including the generated images.  I hope to release it by the end of this month.  If you wish to disable all images, you can omit the `-si` flag currently.

Thank you.

**Comment by Breakthrough** [comment] 2018-07-14 15:56
Closing as duplicate of #45.

**Closed by Breakthrough** 2018-07-14 15:56 UTC
Labels: status: duplicate
