### ISSUE TITLE
can`t save_images in scenedetect

### ISSUE THREAD

**Issue by Vsevosemnog** [Breakthrough/PySceneDetect#348] opened 2023-08-21 20:22 UTC
I have a scene list
```
[(00:18:17.467 [frame=32924, fps=30.000], 00:19:17.467 [frame=34724, fps=30.000]), (00:47:14.200 [frame=85026, fps=30.000], 00:48:14.200 [frame=86826, fps=30.000]), (00:48:14.200 [frame=86826, fps=30.000], 00:49:14.200 [frame=88626, fps=30.000]), (00:49:14.200 [frame=88626, fps=30.000], 00:50:14.200 [frame=90426, fps=30.000]), (00:50:14.200 [frame=90426, fps=30.000], 00:51:14.200 [frame=92226, fps=30.000]), (00:51:43.333 [frame=93100, fps=30.000], 00:52:43.333 [frame=94900, fps=30.000]), (00:52:43.333 [frame=94900, fps=30.000], 00:52:48.533 [frame=95056, fps=30.000]), (00:59:41.667 [frame=107450, fps=30.000], 01:00:36.467 [frame=109094, fps=30.000]), (01:00:36.467 [frame=109094, fps=30.000], 01:01:36.467 [frame=110894, fps=30.000]), (01:01:36.467 [frame=110894, fps=30.000], 01:02:36.467 [frame=112694, fps=30.000]), (01:02:52.933 [frame=113188, fps=30.000], 01:03:52.933 [frame=114988, fps=30.000]), (01:04:17.067 [frame=115712, fps=30.000], 01:05:17.067 [frame=117512, fps=30.000]), (01:05:17.067 [frame=117512, fps=30.000], 01:06:17.067 [frame=119312, fps=30.000])]
```
I try to save some screenshots from scenes to file but i get error
```
help_vid = open_video(clip_path)
write_scene_list_html(output_html_filename="%s_before_concat_list.html" % clip_path, scene_list=output_scene)
save_images(video=help_vid,scene_list=output_scene, num_images = 5, image_name_template="%s_help_$SCENE_NUMBER-$IMAGE_NUMBER.mp4"%clip_path , width=200, height=200)
```
![image](https://github.com/Breakthrough/PySceneDetect/assets/37411749/7073087f-4d69-497d-8901-67813311e5e8)
Could you please help, can`t understand what i`ve done wrong

If this is just a warning how to ignore it and continue my script?

**Comment by wjs018** [comment] 2023-08-21 21:55
This error is indicating that decoding the desired frame of the video was not successful. The `save_images` function seeks to the desired frame to pull as an image [here ](https://github.com/Breakthrough/PySceneDetect/blob/4b89b6a5b567610455d6f1ac5dd11a3783581cea/scenedetect/scene_manager.py#L488) and then calls the `read` function to decode the desired frame in the next line. It's not clear which backend you are using, but you can see the [docstring](https://github.com/Breakthrough/PySceneDetect/blob/4b89b6a5b567610455d6f1ac5dd11a3783581cea/scenedetect/backends/opencv.py#L265) for the `read` function when using the OpenCV backend (the default backend) that it is supposed to return a decoded numpy array and a boolean. In cases in which the decoding is not successful, then just a boolean is returned. This would cause the error that you see here.

Does this happen with other videos, or is it specific to one video?

**Comment by Vsevosemnog** [comment] 2023-08-22 02:10
> 

yes, this happens to other videos as well

**Comment by Breakthrough** [comment] 2023-08-22 22:57
Does the issue still happen once you re-encode (or re-mux) the input video?  The OpenCV backend tries to recover from this gracefully, so I assume seeking isn't happening correctly for this video.

As in #345, do the other videos this happens with also have trouble seeking?

**Comment by Vsevosemnog** [comment] 2023-08-28 10:42
Could you please help me with this error
FrameTimecode instances require equal framerate for addition

**Comment by KerolosAtef** [comment] 2023-09-03 23:46
Could anyone give me the solution? 
I faced the same error

**Comment by Breakthrough** [comment] 2023-09-04 01:29
@KerolosAtef  Can you try the PyAV backend?  Otherwise you may have to re-encode / re-mux the source material first.

Can you provide a sample of a clip that causes this error?  If anyone can provide a reproduction of the issue, that would be very helpful.

**Comment by Breakthrough** [comment] 2024-04-20 01:36
Closing this issue due to lack of context, feel free to re-open or file a new one if this still occurs.

**Closed by Breakthrough** 2024-04-20 01:36 UTC
Labels: bug, awaiting response
