### ISSUE TITLE
Apply detect-content algo in a specified section than the entire frame

### ISSUE THREAD

**Issue by aaronliruns** [Breakthrough/PySceneDetect#328] opened 2023-07-02 09:55 UTC
First of all, this is a fantastic project! Really apprecaite it.

One enhancement I can think of is that to let user to provide parameters of a section on the screen so that the algo will compare the content within than that of the entire frame! 

This is extremely helpful when the user already knows where to look at as a sign of change scene and the the calculation can be reduced a lot.

A particular requirement can be like this - https://stackoverflow.com/questions/68961528/detect-text-change-in-the-corner-of-the-video-and-get-the-timecode. (not raised by me but this can be a very general request)

Please do consider.

Aaron

**Comment by Breakthrough** [comment] 2023-07-08 17:24
Hi @aaronliruns, thanks for the feedback and suggestion.  This is already being tracked in #302 and is planned for an upcoming release.

Closing this as a duplicate of #302 but feel free to add any  other thoughts or suggestions there.  Thank you!

**Closed by Breakthrough** 2023-07-08 17:24 UTC
