### ISSUE TITLE
TypeError: save_to_csv() got an unexpected keyword argument 'path'

### ISSUE THREAD

**Issue by Mensen** [Breakthrough/PySceneDetect#301] opened 2022-11-15 22:46 UTC
**Bug/Issue Description:**
A clear and concise description of what the bug or issue is - in other words, what the *unexpected* behavior or output is.

Only when using the AdaptiveDetector do I receive a TypeError. Seemingly after the actual detection is complete. I tried to explicitly define a path for the stats_file_path but received the same error. Its unclear why this happens (I've tried looking in __init__.py but I'm unsure why the "path" argument is still unexpected.

**Required Information:**
Provide the following information to assist with reporting the bug:
1. Provide a full copy of the command line options you are using, for example:

**scene_list = detect(video_file, AdaptiveDetector())**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\research\python_toolboxes\anaconda_3\envs\video_edits\lib\site-packages\scenedetect\__init__.py", line 194, in detect
    path=stats_file_path, base_timecode=video.base_timecode)
TypeError: save_to_csv() got an unexpected keyword argument 'path'

**>>> scene_list = detect(video_file, AdaptiveDetector(), stats_file_path=base_path)**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\research\python_toolboxes\anaconda_3\envs\video_edits\lib\site-packages\scenedetect\__init__.py", line 194, in detect
    path=stats_file_path, base_timecode=video.base_timecode)
TypeError: save_to_csv() got an unexpected keyword argument 'path'

2. Add `-v debug -l BUG_REPORT.txt` to the beginning of the command, then re-run PySceneDetect and **attach the generated `BUG_REPORT.txt` file**.

_Unfortunately I'm not sure how to generate this when running within python_

**Expected Behavior:**

I expect the detection to run without this error and return the same list of scenes as with the other detector options.

**Computing Environment:**
 - OS: Windows
 - Python Version: 3.7.12
 - OpenCV Version: 4.6.0.66

**Comment by wjs018** [comment] 2022-11-15 22:51
Duplicate of #299. Currently there is a PR to address this, #300 (hopefully merged soon). Will mark this as closed to consolidate discussion over there.

**Closed by wjs018** 2022-11-15 22:51 UTC

**Comment by Mensen** [comment] 2022-11-16 17:09
I can confirm the fix works for the issue I had.
